export interface FailureQuotes {
  quote: string;
}

export const FailQuotes: FailureQuotes[] = [
  { quote: 'Failure is just a step toward success!' },
  { quote: 'Every setback is a setup for a comeback.' },
  { quote: 'Keep going. Progress beats perfection.' },
  { quote: "Mistakes are proof you're trying!" },
  { quote: "It's okay to pause, just don’t stop!" },
  { quote: 'Small steps still move you forward.' },
  { quote: 'You’re closer than you were yesterday.' },
  { quote: 'The best is yet to come!' },
  { quote: 'Success is built on lessons from failure.' },
  { quote: "Don’t quit, you're halfway there!" },
  { quote: 'Progress, not perfection.' },
  { quote: 'You can always try again tomorrow.' },
  { quote: 'A stumble is not a fall.' },
  { quote: 'Failure is temporary, quitting is permanent.' },
  { quote: 'You haven’t failed until you quit trying.' },
  { quote: 'Keep pushing, your goal is within reach.' },
  { quote: 'Learn from the mistake, then let it go.' },
  { quote: 'Every failure is a learning opportunity.' },
  { quote: 'You are stronger than you think!' },
  { quote: 'Turn today’s failure into tomorrow’s victory.' },
  { quote: 'Great things take time. Keep going!' },
  { quote: 'You’ve got this. Try again!' },
  { quote: "Keep climbing, you're almost there." },
  { quote: 'Perseverance leads to success.' },
  { quote: 'You’re learning. Keep going.' },
  { quote: 'One step at a time. You’ll get there!' },
  { quote: 'Mistakes make you stronger.' },
  { quote: 'Don’t be discouraged, be determined!' },
  { quote: 'You’ve already made progress by trying.' },
  { quote: 'The road to success is paved with persistence.' },
  { quote: 'Failures are the stepping stones to success.' },
  { quote: 'Rise after every fall.' },
  { quote: 'Don’t let one setback stop your progress.' },
  { quote: 'You only truly fail when you stop trying.' },
  { quote: 'Tomorrow is a fresh start.' },
  { quote: 'Your effort is never wasted.' },
  { quote: 'You’ve survived tough days before, you can do it again.' },
  { quote: 'Fall down seven times, stand up eight.' },
  { quote: 'Believe in the power of persistence.' },
  { quote: 'Your hard work will pay off.' },
  { quote: 'Take a breath, then try again.' },
  { quote: 'Success is built on failure.' },
  { quote: 'Every no gets you closer to a yes.' },
  { quote: 'Today’s struggle is tomorrow’s strength.' },
  { quote: 'You’re on your way, don’t give up now!' },
  { quote: 'Failure is feedback, use it!' },
  { quote: 'Success is just around the corner.' },
  { quote: 'Every setback is an opportunity for a comeback.' },
  { quote: 'You are capable of amazing things!' },
  { quote: 'One more try can make all the difference.' },
  { quote: 'You’ve got what it takes to succeed.' },
  { quote: 'Don’t let failure be your final chapter.' },
  { quote: 'Keep moving forward, no matter how small the step.' },
  { quote: 'Persistence conquers all.' },
  { quote: 'Failure builds resilience.' },
  { quote: 'Tomorrow is a chance to do better.' },
  { quote: 'You’re one step closer to success.' },
  { quote: 'Success is built on trying again.' },
  { quote: 'One setback won’t stop your journey.' },
  { quote: 'Don’t let failure define you, let it refine you.' },
  { quote: 'Turn your setbacks into setups for success.' },
  { quote: 'Learn from it, then move forward.' },
  { quote: 'Success comes to those who persist.' },
  { quote: 'You can’t fail if you don’t give up.' },
  { quote: 'You’ll bounce back stronger.' },
  { quote: 'Failure isn’t the end, it’s part of the process.' },
  { quote: 'Keep your eyes on the goal, not the obstacle.' },
  { quote: 'You’re still in the race, keep going!' },
  { quote: 'Failure is part of the process of success.' },
  { quote: 'You’ve got the strength to keep trying.' },
  { quote: 'Great things take time, keep going.' },
  { quote: 'A detour is just a different path to success.' },
  { quote: 'Every failure brings you closer to success.' },
  { quote: 'Believe in the power of persistence.' },
  { quote: 'You’re closer than you were yesterday.' },
  { quote: 'Don’t stop now, you’re almost there!' },
  { quote: 'Failure teaches what success can’t.' },
  { quote: 'The harder the battle, the sweeter the victory.' },
  { quote: 'Every challenge is a chance to grow.' },
  { quote: 'You are stronger than any setback.' },
  { quote: 'A temporary failure isn’t a permanent defeat.' },
  { quote: "Try again. You'll get it next time." },
  { quote: 'You’ve come too far to quit now.' },
  { quote: 'Your effort is the key to success.' },
  { quote: 'Great achievements require great perseverance.' },
  { quote: 'One small failure can’t stop your big dreams.' },
  { quote: 'You’re only one step away from progress.' },
  { quote: 'Don’t count your losses, count your lessons.' },
  { quote: 'Success is built on determination.' },
  { quote: 'You’re closer to your goal than you realize.' },
  { quote: 'The next try could be the one!' },
  { quote: 'Failure is an event, not a person.' },
  { quote: 'You’re capable of amazing things!' },
  { quote: 'Small progress is still progress.' },
  { quote: 'You’ve learned, now try again.' },
  { quote: 'Even small steps bring you closer.' },
  { quote: 'Turn your mistakes into your motivation.' },
  { quote: 'Don’t let a single failure define your journey.' },
  { quote: 'You’re stronger than you think.' },
  { quote: 'Success is a journey, not a destination.' },
  { quote: 'You are building something great, keep going!' },
  { quote: 'Your efforts today build your success tomorrow.' },
  { quote: 'You’re only one step away from a breakthrough.' },
  { quote: "Keep trying, you're almost there." },
  { quote: 'Success is one step beyond failure.' },
  { quote: 'Persistence makes the impossible possible.' },
  { quote: 'The journey is long, but the reward is worth it.' },
  { quote: 'One setback won’t stop your momentum.' },
  { quote: 'You’ve got what it takes to succeed!' },
  { quote: 'Keep moving forward, you’re doing great!' },
  { quote: 'Failure is part of the learning process.' },
  { quote: 'The road to success is paved with persistence.' },
  { quote: "Don't let today's failure stop tomorrow's progress." },
  { quote: 'Your hard work will pay off, don’t quit!' },
  { quote: 'Every challenge is a chance for growth.' },
  { quote: 'You’ve already come so far. Keep going!' },
  { quote: 'One setback doesn’t erase your progress.' },
  { quote: 'Keep the faith in your abilities.' },
  { quote: 'Your best is yet to come!' },
  { quote: 'Tomorrow brings a new chance to succeed.' },
  { quote: 'Success is just one more try away.' },
  { quote: 'Every fall brings a new rise.' },
  { quote: "Believe in yourself, you've got this!" },
  { quote: 'Keep your eyes on the goal, not the failure.' },
  { quote: 'You’ve got the strength to continue.' },
  { quote: "Don't let a failure halt your journey." },
  { quote: 'Success is built on persistence, keep going!' },
  { quote: 'You’re one step away from a breakthrough.' },
  { quote: 'Turn today’s challenge into tomorrow’s triumph.' },
  { quote: 'You’re learning, growing, and getting stronger!' },
  { quote: 'The journey to success is filled with challenges.' },
  { quote: "Don’t give up, you're closer than you think!" },
];
