export const greetings = [
  'Studying is fun with me!',
  "Let's make studying fun today!",
  "Learning is fun, let's begin!",
  "I'm here, let's study together!",
  'Time to study and have fun!',
  "Let's study, it's going to be fun!",
  'Learning is fun with me!',
  'Let’s dive into fun learning!',
  'Let’s have fun studying together!',
  "I'm ready, let’s study now!",
  "Ready for fun studying? Let's go!",
  'Studying is more fun with me!',
  "Fun learning starts now, let's go!",
  'Study smarter, and have fun!',
  'Let’s study, it’ll be fun!',
  'Fun and learning go together!',
  'Let’s learn, it’s fun together!',
  'Learning is fun, let’s do this!',
  "Let's learn something fun today!",
  "Studying is fun, let's begin!",
];
