export const motivationalPhrases = [
  "You're crushing it! Keep up the momentum!",
  "You're doing an amazing job! Stay focused and keep it going!",
  "Fantastic work! You're on the path to greatness!",
  "Keep shining, you're absolutely nailing it!",
  "You're unstoppable! Keep pushing forward!",
  'Your hard work is paying off—don’t stop now!',
  "You're on fire! Keep that energy up!",
  "Amazing progress! You're getting closer to your goals!",
  "You're a rockstar! Keep showing up like this!",
  "Outstanding effort! You're making it happen!",
  "You're hitting it out of the park! Keep it up!",
  "You're on a roll! Keep the momentum alive!",
  "You're a force to be reckoned with! Keep dominating!",
  "You're making waves! Keep going strong!",
  "Bravo! You're proving how capable you are!",
  "What you're doing is incredible—keep the drive alive!",
  "You're exceeding expectations! Keep raising the bar!",
  "You're smashing through every obstacle! Keep at it!",
  "You're a powerhouse! Keep charging forward!",
  'Your determination is inspiring—stay the course!',
  "You're making it look easy! Keep up the great work!",
];
